### ISSUE TITLE
Inifinity generating world

### ISSUE THREAD

**Issue by VinkyV** [GroupMountain/FuckNetherHeight#3]
LL: 0.8.1
BDS: 1.20.61
When i enter nether it stops on generating world...

**Comment by VinkyV** [comment]
Fix
```cpp
LL_AUTO_TYPE_INSTANCE_HOOK(
    LevelChunkPacketWrite,
    ll::memory::HookPriority::Lowest,
    LevelChunkPacket,
    "?write@LevelChunkPacket@@UEBAXAEAVBinaryStream@@@Z",
    void,
    BinaryStream const& bs
) {
    if (this->mDimensionType == 1) {
        this->mDimensionType = 2;
    }
    return origin(bs);
}
```

**Comment by Tsubasa6848** [comment]
Thanks for your codes. I will fix it tomorrow. 
Next time if you found a bug and you know how to fix it, you can make a  Pull Request. 

In addition, if you teleport from nether to the end, will also cause this issue. I will also fix it.

**Comment by Tsubasa6848** [comment]
fixed
